package zhook.aohoc.a;

/* loaded from: classes.dex */
public class f {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static String[] ah;
    public static String[] ai;
    private static int aj;
    private static String[] ak;
    private static int al;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        aj = 0;
        int i2 = aj;
        aj = i2 + 1;
        a = i2;
        int i3 = aj;
        aj = i3 + 1;
        b = i3;
        int i4 = aj;
        aj = i4 + 1;
        c = i4;
        int i5 = aj;
        aj = i5 + 1;
        d = i5;
        int i6 = aj;
        aj = i6 + 1;
        e = i6;
        int i7 = aj;
        aj = i7 + 1;
        f = i7;
        int i8 = aj;
        aj = i8 + 1;
        g = i8;
        int i9 = aj;
        aj = i9 + 1;
        h = i9;
        int i10 = aj;
        aj = i10 + 1;
        i = i10;
        int i11 = aj;
        aj = i11 + 1;
        j = i11;
        int i12 = aj;
        aj = i12 + 1;
        k = i12;
        int i13 = aj;
        aj = i13 + 1;
        l = i13;
        int i14 = aj;
        aj = i14 + 1;
        m = i14;
        int i15 = aj;
        aj = i15 + 1;
        n = i15;
        int i16 = aj;
        aj = i16 + 1;
        o = i16;
        int i17 = aj;
        aj = i17 + 1;
        p = i17;
        int i18 = aj;
        aj = i18 + 1;
        q = i18;
        int i19 = aj;
        aj = i19 + 1;
        r = i19;
        int i20 = aj;
        aj = i20 + 1;
        s = i20;
        int i21 = aj;
        aj = i21 + 1;
        t = i21;
        int i22 = aj;
        aj = i22 + 1;
        u = i22;
        int i23 = aj;
        aj = i23 + 1;
        v = i23;
        int i24 = aj;
        aj = i24 + 1;
        w = i24;
        int i25 = aj;
        aj = i25 + 1;
        x = i25;
        int i26 = aj;
        aj = i26 + 1;
        y = i26;
        int i27 = aj;
        aj = i27 + 1;
        z = i27;
        int i28 = aj;
        aj = i28 + 1;
        A = i28;
        int i29 = aj;
        aj = i29 + 1;
        B = i29;
        int i30 = aj;
        aj = i30 + 1;
        C = i30;
        int i31 = aj;
        aj = i31 + 1;
        D = i31;
        int i32 = aj;
        aj = i32 + 1;
        E = i32;
        int i33 = aj;
        aj = i33 + 1;
        F = i33;
        int i34 = aj;
        aj = i34 + 1;
        G = i34;
        int i35 = aj;
        aj = i35 + 1;
        H = i35;
        int i36 = aj;
        aj = i36 + 1;
        I = i36;
        int i37 = aj;
        aj = i37 + 1;
        J = i37;
        int i38 = aj;
        aj = i38 + 1;
        K = i38;
        int i39 = aj;
        aj = i39 + 1;
        L = i39;
        int i40 = aj;
        aj = i40 + 1;
        M = i40;
        int i41 = aj;
        aj = i41 + 1;
        N = i41;
        int i42 = aj;
        aj = i42 + 1;
        O = i42;
        int i43 = aj;
        aj = i43 + 1;
        P = i43;
        int i44 = aj;
        aj = i44 + 1;
        Q = i44;
        int i45 = aj;
        aj = i45 + 1;
        R = i45;
        int i46 = aj;
        aj = i46 + 1;
        S = i46;
        int i47 = aj;
        aj = i47 + 1;
        T = i47;
        int i48 = aj;
        aj = i48 + 1;
        U = i48;
        int i49 = aj;
        aj = i49 + 1;
        V = i49;
        int i50 = aj;
        aj = i50 + 1;
        W = i50;
        int i51 = aj;
        aj = i51 + 1;
        X = i51;
        int i52 = aj;
        aj = i52 + 1;
        Y = i52;
        int i53 = aj;
        aj = i53 + 1;
        Z = i53;
        int i54 = aj;
        aj = i54 + 1;
        aa = i54;
        int i55 = aj;
        aj = i55 + 1;
        ab = i55;
        int i56 = aj;
        aj = i56 + 1;
        ac = i56;
        int i57 = aj;
        aj = i57 + 1;
        ad = i57;
        int i58 = aj;
        aj = i58 + 1;
        ae = i58;
        int i59 = aj;
        aj = i59 + 1;
        af = i59;
        int i60 = aj;
        aj = i60 + 1;
        ag = i60;
    }

    public static void a(int i2) {
        String[] a2 = ag.a(ag.b("text_" + ai[i2].toLowerCase() + ".txt"), '\n');
        for (int i3 = 0; i3 < a2.length; i3++) {
            a2[i3] = ag.a(a2[i3], "\\n", "\n");
        }
        ak = a2;
        al = i2;
    }

    public static String b(int i2) {
        if (i2 >= ak.length) {
            return null;
        }
        return ak[i2];
    }
}
