package zhook.aohoc.a.b;

/* loaded from: classes.dex */
public class b {
    public static final int A;
    public static final int B;
    public static final int C;
    private static int D;
    private static int E;
    private static int F;
    private static int G;
    private static int H;
    public static final int a;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        D = 0;
        int i2 = D;
        D = i2 + 1;
        a = i2;
        b = D;
        E = 0;
        int i3 = E;
        E = i3 + 1;
        c = i3;
        int i4 = E;
        E = i4 + 1;
        d = i4;
        int i5 = E;
        E = i5 + 1;
        e = i5;
        int i6 = E;
        E = i6 + 1;
        f = i6;
        int i7 = E;
        E = i7 + 1;
        g = i7;
        int i8 = E;
        E = i8 + 1;
        h = i8;
        i = E;
        F = 0;
        int i9 = F;
        F = i9 + 1;
        j = i9;
        int i10 = F;
        F = i10 + 1;
        k = i10;
        int i11 = F;
        F = i11 + 1;
        l = i11;
        int i12 = F;
        F = i12 + 1;
        m = i12;
        int i13 = F;
        F = i13 + 1;
        n = i13;
        o = F;
        G = 0;
        int i14 = G;
        G = i14 + 1;
        p = i14;
        int i15 = G;
        G = i15 + 1;
        q = i15;
        int i16 = G;
        G = i16 + 1;
        r = i16;
        int i17 = G;
        G = i17 + 1;
        s = i17;
        int i18 = G;
        G = i18 + 1;
        t = i18;
        int i19 = G;
        G = i19 + 1;
        u = i19;
        v = G;
        H = 0;
        int i20 = H;
        H = i20 + 1;
        w = i20;
        int i21 = H;
        H = i21 + 1;
        x = i21;
        int i22 = H;
        H = i22 + 1;
        y = i22;
        int i23 = H;
        H = i23 + 1;
        z = i23;
        int i24 = H;
        H = i24 + 1;
        A = i24;
        int i25 = H;
        H = i25 + 1;
        B = i25;
        C = H;
    }
}
