package zhook.aohoc.a.b;

/* loaded from: classes.dex */
public class c {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    private static int aA;
    private static int aB;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int ap;
    public static final int aq;
    public static final int ar;
    public static final int as;
    public static final int at;
    public static final int au;
    public static final int av;
    private static int aw;
    private static int ax;
    private static int ay;
    private static int az;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        aw = 0;
        int i2 = aw;
        aw = i2 + 1;
        a = i2;
        int i3 = aw;
        aw = i3 + 1;
        b = i3;
        int i4 = aw;
        aw = i4 + 1;
        c = i4;
        int i5 = aw;
        aw = i5 + 1;
        d = i5;
        int i6 = aw;
        aw = i6 + 1;
        e = i6;
        int i7 = aw;
        aw = i7 + 1;
        f = i7;
        int i8 = aw;
        aw = i8 + 1;
        g = i8;
        int i9 = aw;
        aw = i9 + 1;
        h = i9;
        int i10 = aw;
        aw = i10 + 1;
        i = i10;
        int i11 = aw;
        aw = i11 + 1;
        j = i11;
        int i12 = aw;
        aw = i12 + 1;
        k = i12;
        int i13 = aw;
        aw = i13 + 1;
        l = i13;
        int i14 = aw;
        aw = i14 + 1;
        m = i14;
        int i15 = aw;
        aw = i15 + 1;
        n = i15;
        int i16 = aw;
        aw = i16 + 1;
        o = i16;
        int i17 = aw;
        aw = i17 + 1;
        p = i17;
        int i18 = aw;
        aw = i18 + 1;
        q = i18;
        int i19 = aw;
        aw = i19 + 1;
        r = i19;
        int i20 = aw;
        aw = i20 + 1;
        s = i20;
        int i21 = aw;
        aw = i21 + 1;
        t = i21;
        int i22 = aw;
        aw = i22 + 1;
        u = i22;
        int i23 = aw;
        aw = i23 + 1;
        v = i23;
        int i24 = aw;
        aw = i24 + 1;
        w = i24;
        int i25 = aw;
        aw = i25 + 1;
        x = i25;
        y = aw;
        ax = 0;
        int i26 = ax;
        ax = i26 + 1;
        z = i26;
        int i27 = ax;
        ax = i27 + 1;
        A = i27;
        B = ax;
        ay = 0;
        int i28 = ay;
        ay = i28 + 1;
        C = i28;
        int i29 = ay;
        ay = i29 + 1;
        D = i29;
        E = ay;
        az = 0;
        int i30 = az;
        az = i30 + 1;
        F = i30;
        int i31 = az;
        az = i31 + 1;
        G = i31;
        int i32 = az;
        az = i32 + 1;
        H = i32;
        int i33 = az;
        az = i33 + 1;
        I = i33;
        int i34 = az;
        az = i34 + 1;
        J = i34;
        int i35 = az;
        az = i35 + 1;
        K = i35;
        int i36 = az;
        az = i36 + 1;
        L = i36;
        int i37 = az;
        az = i37 + 1;
        M = i37;
        int i38 = az;
        az = i38 + 1;
        N = i38;
        int i39 = az;
        az = i39 + 1;
        O = i39;
        int i40 = az;
        az = i40 + 1;
        P = i40;
        int i41 = az;
        az = i41 + 1;
        Q = i41;
        int i42 = az;
        az = i42 + 1;
        R = i42;
        int i43 = az;
        az = i43 + 1;
        S = i43;
        int i44 = az;
        az = i44 + 1;
        T = i44;
        int i45 = az;
        az = i45 + 1;
        U = i45;
        int i46 = az;
        az = i46 + 1;
        V = i46;
        int i47 = az;
        az = i47 + 1;
        W = i47;
        X = az;
        aA = 0;
        int i48 = aA;
        aA = i48 + 1;
        Y = i48;
        int i49 = aA;
        aA = i49 + 1;
        Z = i49;
        int i50 = aA;
        aA = i50 + 1;
        aa = i50;
        int i51 = aA;
        aA = i51 + 1;
        ab = i51;
        int i52 = aA;
        aA = i52 + 1;
        ac = i52;
        int i53 = aA;
        aA = i53 + 1;
        ad = i53;
        int i54 = aA;
        aA = i54 + 1;
        ae = i54;
        int i55 = aA;
        aA = i55 + 1;
        af = i55;
        int i56 = aA;
        aA = i56 + 1;
        ag = i56;
        int i57 = aA;
        aA = i57 + 1;
        ah = i57;
        int i58 = aA;
        aA = i58 + 1;
        ai = i58;
        int i59 = aA;
        aA = i59 + 1;
        aj = i59;
        ak = aA;
        aB = 0;
        int i60 = aB;
        aB = i60 + 1;
        al = i60;
        int i61 = aB;
        aB = i61 + 1;
        am = i61;
        int i62 = aB;
        aB = i62 + 1;
        an = i62;
        int i63 = aB;
        aB = i63 + 1;
        ao = i63;
        int i64 = aB;
        aB = i64 + 1;
        ap = i64;
        int i65 = aB;
        aB = i65 + 1;
        aq = i65;
        int i66 = aB;
        aB = i66 + 1;
        ar = i66;
        int i67 = aB;
        aB = i67 + 1;
        as = i67;
        int i68 = aB;
        aB = i68 + 1;
        at = i68;
        int i69 = aB;
        aB = i69 + 1;
        au = i69;
        av = aB;
    }
}
