package zhook.aohoc.a.b;

/* loaded from: classes.dex */
public class e {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    private static int I;
    private static int J;
    private static int K;
    private static int L;
    private static int M;
    private static int N;
    public static final int a;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;

    static {
        I = 0;
        int i2 = I;
        I = i2 + 1;
        a = i2;
        int i3 = I;
        I = i3 + 1;
        b = i3;
        int i4 = I;
        I = i4 + 1;
        c = i4;
        int i5 = I;
        I = i5 + 1;
        d = i5;
        int i6 = I;
        I = i6 + 1;
        e = i6;
        int i7 = I;
        I = i7 + 1;
        f = i7;
        int i8 = I;
        I = i8 + 1;
        g = i8;
        int i9 = I;
        I = i9 + 1;
        h = i9;
        int i10 = I;
        I = i10 + 1;
        i = i10;
        j = I;
        J = 0;
        int i11 = J;
        J = i11 + 1;
        k = i11;
        int i12 = J;
        J = i12 + 1;
        l = i12;
        int i13 = J;
        J = i13 + 1;
        m = i13;
        int i14 = J;
        J = i14 + 1;
        n = i14;
        int i15 = J;
        J = i15 + 1;
        o = i15;
        p = J;
        K = 0;
        int i16 = K;
        K = i16 + 1;
        q = i16;
        int i17 = K;
        K = i17 + 1;
        r = i17;
        int i18 = K;
        K = i18 + 1;
        s = i18;
        int i19 = K;
        K = i19 + 1;
        t = i19;
        u = K;
        L = 0;
        int i20 = L;
        L = i20 + 1;
        v = i20;
        int i21 = L;
        L = i21 + 1;
        w = i21;
        int i22 = L;
        L = i22 + 1;
        x = i22;
        int i23 = L;
        L = i23 + 1;
        y = i23;
        int i24 = L;
        L = i24 + 1;
        z = i24;
        int i25 = L;
        L = i25 + 1;
        A = i25;
        B = L;
        M = 0;
        int i26 = M;
        M = i26 + 1;
        C = i26;
        D = M;
        N = 0;
        int i27 = N;
        N = i27 + 1;
        E = i27;
        int i28 = N;
        N = i28 + 1;
        F = i28;
        int i29 = N;
        N = i29 + 1;
        G = i29;
        H = N;
    }
}
